# fly.toml file generated for dirtbag-backend on 2023-02-18T18:09:40+01:00

app = "fistbump-backend"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

#  [[services.http_checks]]
#    interval = 10000
#    grace_period = "5s"
#    method = "get"
#    path = "/healtz"
#    protocol = "http"
#    restart_limit = 0
#    timeout = 2000
#    tls_skip_verify = false

#  [services.http_checks.headers]

  [mounts]
    source = "fistbump_data"
    destination = "/data"

  [metrics]
    port = 9091       # default for most prometheus clients
    path = "/metrics" # default for most prometheus clients

