# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: fistbump

on:
  push:
    paths:
      - "backend/**/*"
      - ".github/workflows/backend.yml"
    branches: [ "main" ]
  pull_request:
    paths:
      - "backend/**/*"
      - ".github/workflows/backend.yml"
    branches: [ "main" ]

permissions:
  contents: read


env:
  STATIC_DIRECTORY: /tmp
  PROBLEM_DB_FILE: /tmp/problems.json
  STOKT_TOKEN: ${{ secrets.STOKT_TOKEN }}
  GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
  GOOGLE_MAPS_PLACE_ID: ChIJ7etYrU1SUkYRu9v7IHXpF5c
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest anyio
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest